{{- if .Values.spc.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "chart.fullname" . }}-spc
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.spc.provider }}
  parameters:
    vaultAddress: {{ .Values.spc.vaultAddress }}
    roleName: {{ .Values.spc.roleName }}  
    objects: |
      {{- range .Values.spc.objects }}
        - objectName: {{ .secretKey }}
          secretPath: {{ .secretPath }}
          secretKey: {{ .secretKey }}
      {{- end }}
      
{{- end }}