repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: secrets-store-csi-driver
    url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

releases:
  - name: postgres-operator
    namespace: db
    chart: postgres-operator-charts/postgres-operator
  - name: ingress-external
    namespace: ingress-external
    chart: ingress-nginx/ingress-nginx
    set:
      - name: controller.replicaCount
        value: 1
      - name: controller.ingressClass
        value: ingress-external
      - name: controller.ingressClassResource.name
        value: ingress-external
      - name: controller.hostNetwork
        value: true
  - name: vault
    namespace: vault
    chart: hashicorp/vault
    values:
      - vault-overrides.yaml
  - name: csi
    namespace: csi
    chart: secrets-store-csi-driver/secrets-store-csi-driver
    set:
      - name: syncSecret.enabled
        value: true
