nameOverride: my-budget-frontend
fullnameOverride: my-budget-frontend

replicaCount: 1

ingress:
  enabled: true
  className: ingress-external
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: my-budget.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - my-budget.xyz
      secretName: my-budget-frontend-tls

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

serviceAccount:
  create: true
  name: my-budget-frontend-sa

image:
  repository: ghcr.io/wardzinskim/my-budget.frontend
  pullPolicy: IfNotPresent
  tag: main

spc:
  enabled: true
  provider: vault
  vaultAddress: http://vault.vault.svc.cluster.local:8200
  roleName: my-budget-frontend-sa
  volumeName: secrets
  objects:
    - secretPath: "kv/data/app/mybudget.frontend/config.js"
      secretKey: "config.js"
      mountPath: "/usr/share/nginx/html/assets/config.js"
    - secretPath: "kv/data/app/mybudget.frontend/nginx.conf"
      secretKey: "nginx.conf"
      mountPath: "/etc/nginx/conf.d/default.conf"
