apiVersion: "acid.zalan.do/v1"
kind: postgresql

metadata:
  name: my-budget-postgres-cluster
  namespace: db

spec:
  teamId: "my-budget"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    administrator:
      - superuser
      - createdb
    my_budget_identity_user: []
    my_budget_user: []
  databases:
    my_budget_identity: my_budget_identity_user
    my_budget: my_budget_user
  postgresql:
    version: "16"
    parameters:
      password_encryption: scram-sha-256
