global:
  enabled: true
  tlsDisable: true
  resources:
    limits:
      memory: 256Mi
      cpu: 250m

server:
  # For HA configuration and because we need to manually init the vault,
  # we need to define custom readiness/liveness Probe settings
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60

  standalone:
    enabled: false

  dataStorage:
    size: 10Gi

  # Run Vault in "HA" mode.
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true
        cluster_name = "vault-integrated-storage"
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
          }
        }

        service_registration "kubernetes" {}

  ingress:
    enabled: true
    activeService: false
    ingressClassName: ingress-external
    hosts:
      - host: vault.my-budget.xyz
    annotations: |
      kubernetes.io/ingress.class: ingress-external
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      - hosts:
          - vault.my-budget.xyz
        secretName: example-tls

# Vault UI
ui:
  enabled: true
  serviceType: "ClusterIP"
  serviceNodePort: null
  externalPort: 8200

csi:
  enabled: true
