/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BudgetDTOStatus } from './budget-dtostatus';
// May contain unused imports in some cases
// @ts-ignore
import { CategoryDTO } from './category-dto';

/**
 *
 * @export
 * @interface BudgetDTO
 */
export interface BudgetDTO {
  /**
   *
   * @type {string}
   * @memberof BudgetDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof BudgetDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof BudgetDTO
   */
  description?: string | null;
  /**
   *
   * @type {BudgetDTOStatus}
   * @memberof BudgetDTO
   */
  status?: BudgetDTOStatus;
  /**
   *
   * @type {Array<CategoryDTO>}
   * @memberof BudgetDTO
   */
  categories?: Array<CategoryDTO> | null;
}
