/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { BudgetDTOStatus } from './budget-dtostatus';

/**
 *
 * @export
 * @interface BudgetListItemDTO
 */
export interface BudgetListItemDTO {
  /**
   *
   * @type {string}
   * @memberof BudgetListItemDTO
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof BudgetListItemDTO
   */
  name?: string | null;
  /**
   *
   * @type {string}
   * @memberof BudgetListItemDTO
   */
  description?: string | null;
  /**
   *
   * @type {Date}
   * @memberof BudgetListItemDTO
   */
  creationDate?: Date;
  /**
   *
   * @type {BudgetDTOStatus}
   * @memberof BudgetListItemDTO
   */
  status?: BudgetDTOStatus;
}
