/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CategoryValue
 */
export interface CategoryValue {
  /**
   *
   * @type {string}
   * @memberof CategoryValue
   */
  category?: string | null;
  /**
   *
   * @type {number}
   * @memberof CategoryValue
   */
  value?: number;
}
