/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ShareDTO
 */
export interface ShareDTO {
  /**
   *
   * @type {string}
   * @memberof ShareDTO
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof ShareDTO
   */
  login?: string | null;
}
