/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TransferDTO } from './transfer-dto';

/**
 *
 * @export
 * @interface TransfersQueryResponse
 */
export interface TransfersQueryResponse {
  /**
   *
   * @type {Date}
   * @memberof TransfersQueryResponse
   */
  dateFrom?: Date;
  /**
   *
   * @type {Date}
   * @memberof TransfersQueryResponse
   */
  dateTo?: Date;
  /**
   *
   * @type {Array<TransferDTO>}
   * @memberof TransfersQueryResponse
   */
  transfers?: Array<TransferDTO> | null;
}
