/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateTransferRequest
 */
export interface UpdateTransferRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransferRequest
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferRequest
     */
    'currency'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferRequest
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransferRequest
     */
    'category'?: string | null;
}

