version: '3.4'

services:
  mybudget.api:
    image: ${DOCKER_REGISTRY-}mybudgetapi
    build:
      context: ../
      dockerfile: MyBudget.Api/Dockerfile

  mybudget.identity:
    image: ${DOCKER_REGISTRY-}mybudgetidentity
    build:
      context: ..
      dockerfile: Identity/MyBudget.Identity/Dockerfile

  seq:
    image: datalust/seq:latest
    ports:
     - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - seq-data:/data

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "1qaz@WSX"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql 


volumes:
  seq-data:
  mssql-data:
