services:
  mybudget.api:
    image: ${DOCKER_REGISTRY-}mybudgetapi
    build:
      context: ../
      dockerfile: MyBudget.Api/Dockerfile

  mybudget.identity.app:
    image: ${DOCKER_REGISTRY-}mybudgetidentity
    build:
      context: ..
      dockerfile: Identity/MyBudget.Identity/Dockerfile

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - seq-data:/data

  postgres:
    container_name: postgres
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1qaz@WSX
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data


volumes:
  seq-data:
  postgresql-data:
    driver: local
