version: '3.4'

services:
  mybudget.api:
    image: ${DOCKER_REGISTRY-}mybudgetapi
    build:
      context: ../
      dockerfile: MyBudget.Api/Dockerfile

  mybudget.identity:
    image: ${DOCKER_REGISTRY-}mybudgetidentity
    build:
      context: ..
      dockerfile: Identity/MyBudget.Identity/Dockerfile

  seq:
    image: datalust/seq:latest
    ports:
     - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - seq-data:/data

  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci



volumes:
  seq-data:
  mysql-data:
