/* tslint:disable */
/* eslint-disable */
/**
 * MyBudget API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from '../base';
// @ts-ignore
import { BudgetDTO } from '../model';
// @ts-ignore
import { BudgetListItemDTO } from '../model';
// @ts-ignore
import { CreateBudgetCategoryRequest } from '../model';
// @ts-ignore
import { CreateBudgetRequest } from '../model';
// @ts-ignore
import { CreateTransferRequest } from '../model';
// @ts-ignore
import { HttpValidationProblemDetails } from '../model';
// @ts-ignore
import { ProblemDetails } from '../model';
// @ts-ignore
import { TransferDTOType } from '../model';
// @ts-ignore
import { TransfersQueryResponse } from '../model';
// @ts-ignore
import { UpdateTransferRequest } from '../model';
/**
 * BudgetApi - axios parameter creator
 * @export
 */
export const BudgetApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {string} id
     * @param {CreateTransferRequest} createTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addTransfer: async (
      id: string,
      createTransferRequest: CreateTransferRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('addTransfer', 'id', id);
      // verify required parameter 'createTransferRequest' is not null or undefined
      assertParamExists(
        'addTransfer',
        'createTransferRequest',
        createTransferRequest
      );
      const localVarPath = `/budget/{id}/transfer`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createTransferRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    archiveBudgetCategory: async (
      id: string,
      name: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('archiveBudgetCategory', 'id', id);
      // verify required parameter 'name' is not null or undefined
      assertParamExists('archiveBudgetCategory', 'name', name);
      const localVarPath = `/budget/{id}/category/{name}/archive`
        .replace(`{${'id'}}`, encodeURIComponent(String(id)))
        .replace(`{${'name'}}`, encodeURIComponent(String(name)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {CreateBudgetRequest} createBudgetRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBudget: async (
      createBudgetRequest: CreateBudgetRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'createBudgetRequest' is not null or undefined
      assertParamExists(
        'createBudget',
        'createBudgetRequest',
        createBudgetRequest
      );
      const localVarPath = `/budget`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createBudgetRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {CreateBudgetCategoryRequest} createBudgetCategoryRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBudgetCategory: async (
      id: string,
      createBudgetCategoryRequest: CreateBudgetCategoryRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('createBudgetCategory', 'id', id);
      // verify required parameter 'createBudgetCategoryRequest' is not null or undefined
      assertParamExists(
        'createBudgetCategory',
        'createBudgetCategoryRequest',
        createBudgetCategoryRequest
      );
      const localVarPath = `/budget/{id}/category`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createBudgetCategoryRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTransfer: async (
      id: string,
      transferId: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('deleteTransfer', 'id', id);
      // verify required parameter 'transferId' is not null or undefined
      assertParamExists('deleteTransfer', 'transferId', transferId);
      const localVarPath = `/budget/{id}/transfer/{transferId}`
        .replace(`{${'id'}}`, encodeURIComponent(String(id)))
        .replace(`{${'transferId'}}`, encodeURIComponent(String(transferId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'DELETE',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBudget: async (
      id: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('getBudget', 'id', id);
      const localVarPath = `/budget/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBudgets: async (
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/budget`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {TransferDTOType} [type]
     * @param {Date} [dateFrom]
     * @param {Date} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTransfers: async (
      id: string,
      type?: TransferDTOType,
      dateFrom?: Date,
      dateTo?: Date,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('getTransfers', 'id', id);
      const localVarPath = `/budget/{id}/transfer`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (type !== undefined) {
        localVarQueryParameter['type'] = type;
      }

      if (dateFrom !== undefined) {
        localVarQueryParameter['dateFrom'] =
          (dateFrom as any) instanceof Date
            ? (dateFrom as any).toISOString()
            : dateFrom;
      }

      if (dateTo !== undefined) {
        localVarQueryParameter['dateTo'] =
          (dateTo as any) instanceof Date
            ? (dateTo as any).toISOString()
            : dateTo;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {UpdateTransferRequest} updateTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTransfer: async (
      id: string,
      transferId: string,
      updateTransferRequest: UpdateTransferRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('updateTransfer', 'id', id);
      // verify required parameter 'transferId' is not null or undefined
      assertParamExists('updateTransfer', 'transferId', transferId);
      // verify required parameter 'updateTransferRequest' is not null or undefined
      assertParamExists(
        'updateTransfer',
        'updateTransferRequest',
        updateTransferRequest
      );
      const localVarPath = `/budget/{id}/transfer/{transferId}`
        .replace(`{${'id'}}`, encodeURIComponent(String(id)))
        .replace(`{${'transferId'}}`, encodeURIComponent(String(transferId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateTransferRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * BudgetApi - functional programming interface
 * @export
 */
export const BudgetApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = BudgetApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} id
     * @param {CreateTransferRequest} createTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addTransfer(
      id: string,
      createTransferRequest: CreateTransferRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addTransfer(
        id,
        createTransferRequest,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.addTransfer']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async archiveBudgetCategory(
      id: string,
      name: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.archiveBudgetCategory(
          id,
          name,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.archiveBudgetCategory']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {CreateBudgetRequest} createBudgetRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createBudget(
      createBudgetRequest: CreateBudgetRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createBudget(
        createBudgetRequest,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.createBudget']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {CreateBudgetCategoryRequest} createBudgetCategoryRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createBudgetCategory(
      id: string,
      createBudgetCategoryRequest: CreateBudgetCategoryRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.createBudgetCategory(
          id,
          createBudgetCategoryRequest,
          options
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.createBudgetCategory']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteTransfer(
      id: string,
      transferId: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTransfer(
        id,
        transferId,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.deleteTransfer']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBudget(
      id: string,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<BudgetDTO>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBudget(
        id,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.getBudget']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBudgets(
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<BudgetListItemDTO>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getBudgets(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.getBudgets']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {TransferDTOType} [type]
     * @param {Date} [dateFrom]
     * @param {Date} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTransfers(
      id: string,
      type?: TransferDTOType,
      dateFrom?: Date,
      dateTo?: Date,
      options?: RawAxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<TransfersQueryResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTransfers(
        id,
        type,
        dateFrom,
        dateTo,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.getTransfers']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {UpdateTransferRequest} updateTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateTransfer(
      id: string,
      transferId: string,
      updateTransferRequest: UpdateTransferRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateTransfer(
        id,
        transferId,
        updateTransferRequest,
        options
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['BudgetApi.updateTransfer']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * BudgetApi - factory interface
 * @export
 */
export const BudgetApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = BudgetApiFp(configuration);
  return {
    /**
     *
     * @param {string} id
     * @param {CreateTransferRequest} createTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addTransfer(
      id: string,
      createTransferRequest: CreateTransferRequest,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .addTransfer(id, createTransferRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    archiveBudgetCategory(
      id: string,
      name: string,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .archiveBudgetCategory(id, name, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {CreateBudgetRequest} createBudgetRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBudget(
      createBudgetRequest: CreateBudgetRequest,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .createBudget(createBudgetRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {CreateBudgetCategoryRequest} createBudgetCategoryRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBudgetCategory(
      id: string,
      createBudgetCategoryRequest: CreateBudgetCategoryRequest,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .createBudgetCategory(id, createBudgetCategoryRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteTransfer(
      id: string,
      transferId: string,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .deleteTransfer(id, transferId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBudget(id: string, options?: any): AxiosPromise<BudgetDTO> {
      return localVarFp
        .getBudget(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBudgets(options?: any): AxiosPromise<Array<BudgetListItemDTO>> {
      return localVarFp
        .getBudgets(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {TransferDTOType} [type]
     * @param {Date} [dateFrom]
     * @param {Date} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTransfers(
      id: string,
      type?: TransferDTOType,
      dateFrom?: Date,
      dateTo?: Date,
      options?: any
    ): AxiosPromise<TransfersQueryResponse> {
      return localVarFp
        .getTransfers(id, type, dateFrom, dateTo, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} transferId
     * @param {UpdateTransferRequest} updateTransferRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateTransfer(
      id: string,
      transferId: string,
      updateTransferRequest: UpdateTransferRequest,
      options?: any
    ): AxiosPromise<void> {
      return localVarFp
        .updateTransfer(id, transferId, updateTransferRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * BudgetApi - interface
 * @export
 * @interface BudgetApi
 */
export interface BudgetApiInterface {
  /**
   *
   * @param {string} id
   * @param {CreateTransferRequest} createTransferRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  addTransfer(
    id: string,
    createTransferRequest: CreateTransferRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;

  /**
   *
   * @param {string} id
   * @param {string} name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  archiveBudgetCategory(
    id: string,
    name: string,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;

  /**
   *
   * @param {CreateBudgetRequest} createBudgetRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  createBudget(
    createBudgetRequest: CreateBudgetRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;

  /**
   *
   * @param {string} id
   * @param {CreateBudgetCategoryRequest} createBudgetCategoryRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  createBudgetCategory(
    id: string,
    createBudgetCategoryRequest: CreateBudgetCategoryRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;

  /**
   *
   * @param {string} id
   * @param {string} transferId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  deleteTransfer(
    id: string,
    transferId: string,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;

  /**
   *
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  getBudget(
    id: string,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<BudgetDTO>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  getBudgets(
    options?: RawAxiosRequestConfig
  ): AxiosPromise<Array<BudgetListItemDTO>>;

  /**
   *
   * @param {string} id
   * @param {TransferDTOType} [type]
   * @param {Date} [dateFrom]
   * @param {Date} [dateTo]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  getTransfers(
    id: string,
    type?: TransferDTOType,
    dateFrom?: Date,
    dateTo?: Date,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<TransfersQueryResponse>;

  /**
   *
   * @param {string} id
   * @param {string} transferId
   * @param {UpdateTransferRequest} updateTransferRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApiInterface
   */
  updateTransfer(
    id: string,
    transferId: string,
    updateTransferRequest: UpdateTransferRequest,
    options?: RawAxiosRequestConfig
  ): AxiosPromise<void>;
}

/**
 * BudgetApi - object-oriented interface
 * @export
 * @class BudgetApi
 * @extends {BaseAPI}
 */
export class BudgetApi extends BaseAPI implements BudgetApiInterface {
  /**
   *
   * @param {string} id
   * @param {CreateTransferRequest} createTransferRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public addTransfer(
    id: string,
    createTransferRequest: CreateTransferRequest,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .addTransfer(id, createTransferRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public archiveBudgetCategory(
    id: string,
    name: string,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .archiveBudgetCategory(id, name, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {CreateBudgetRequest} createBudgetRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public createBudget(
    createBudgetRequest: CreateBudgetRequest,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .createBudget(createBudgetRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {CreateBudgetCategoryRequest} createBudgetCategoryRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public createBudgetCategory(
    id: string,
    createBudgetCategoryRequest: CreateBudgetCategoryRequest,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .createBudgetCategory(id, createBudgetCategoryRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} transferId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public deleteTransfer(
    id: string,
    transferId: string,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .deleteTransfer(id, transferId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public getBudget(id: string, options?: RawAxiosRequestConfig) {
    return BudgetApiFp(this.configuration)
      .getBudget(id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public getBudgets(options?: RawAxiosRequestConfig) {
    return BudgetApiFp(this.configuration)
      .getBudgets(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {TransferDTOType} [type]
   * @param {Date} [dateFrom]
   * @param {Date} [dateTo]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public getTransfers(
    id: string,
    type?: TransferDTOType,
    dateFrom?: Date,
    dateTo?: Date,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .getTransfers(id, type, dateFrom, dateTo, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} transferId
   * @param {UpdateTransferRequest} updateTransferRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetApi
   */
  public updateTransfer(
    id: string,
    transferId: string,
    updateTransferRequest: UpdateTransferRequest,
    options?: RawAxiosRequestConfig
  ) {
    return BudgetApiFp(this.configuration)
      .updateTransfer(id, transferId, updateTransferRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
